services:
  - type: web
    name: my-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free  # Change to 'starter' or 'pro' if needed
    region: oregon  # Modify if necessary
